---
controller_execution_environments:
  - name: "cac"
    description: ""
    organization: "Default"
    image: "quay.io/lagomes/ee-cac-rhel9:v1"
    pull: "missing"
  - name: "ee-openssl-rhel8"
    description: "Projeto de automacao CaC"
    organization: "devops"
    image: "quay.io/lagomes/ee-openssl-rhel8:v6"
    pull: "missing"
  - name: "ee-openvpn-rhel9"
    description: "Projeto de automacao CaC"
    organization: "devops"
    image: "quay.io/lagomes/ee-openvpn:v1"
    pull: "missing"
  - name: "Minimal execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest"
    pull: "missing"
    credential: "Default Execution Environment Registry Credential"
  - name: "Default execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest"
    pull: "missing"
    credential: "Default Execution Environment Registry Credential"
  - name: "Control Plane Execution Environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest"
    pull: "missing"
    credential: "Default Execution Environment Registry Credential"
...
