---
controller_credential_types:
  - name: "Custom GitHub Token Injector"
    description: "{{ description }}"
    kind: cloud
    inputs:
      fields:
        - id: github_token_secret
          label: "GitHub PAT (Token)"
          type: string
          secret: true
          help_text: "Insira o Personal Access Token do GitHub."
      required:
        - github_token_secret

    injectors:
      extra_vars:
        github_token: !unsafe '{{ github_token_secret }}'
      env:
        GITHUB_TOKEN: !unsafe '{{ github_token_secret }}'

  - name: "REST API Credential"
    description: "REST API Credential"
    kind: "cloud"
    inputs:
      fields:
        - id: rest_username
          label: REST Username
          type: string
        - id: rest_password
          label: REST Password
          secret: true
          type: string
      required:
        - rest_username
        - rest_password

    injectors:
      env:
        rest_password_env: !unsafe '{{ rest_password }}'
        rest_username_env: !unsafe '{{ rest_username }}'
      extra_vars:
        rest_password: !unsafe '{{ rest_password }}'
        rest_username: !unsafe '{{ rest_username }}'
