---
controller_credentials:
  - name: "Haproxy - Acesso hosts"
    description: "Projeto de automacao CaC"
    credential_type: "Machine"
    organization: "devops"
    inputs:
      username: root

...
