---
controller_credentials:
  - name: "Haproxy - Acesso HUB"
    description: "Projeto de automacao CaC"
    credential_type: "Container Registry"
    organization: "devops"
    inputs:
      host: automationhub01.conectado.local
      username: lagomes
      verify_ssl: false

...
