---
controller_inventories:
  - name: "Default Blank Localhost Only"
    description: "Projeto de automacao CaC"
    organization: "devops"
    host_filter: ""
    prevent_instance_group_fallback: False
...
